#!/bin/bash

# monocleOS updater - executed by automatic-update.service/timer & respective functions run by pacman hooks
# Copyright (C) 2020  Zack Didcott

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

source /etc/monocleOS.env

function funcSystem {
    optUpdate="-Syu --noconfirm"
    optClean="-Sc --noconfirm"
    systemd-inhibit --why="System Updating..." sudo -u monocle $installer $optUpdate
    systemd-inhibit --why="System Updating..." sudo -u monocle $installer $optClean
}

# Pacman Hook Functions

function funcGrub {
    if [[ $bootloader == "efi" ]]; then
        grub-install --target=$bootloaderArch-efi --efi-directory=$efiPath --bootloader-id=GRUB
        if [[ $secureBoot = 1 ]]; then
            # For secure boot
            cp $efiPath/EFI/GRUB/grubx64.efi $efiPath/EFI/Boot/loader.efi
        fi
    else  # Assume MBR if not EFI
        # Find mapper device, then find physical partition for mapper (LVM on LUKS) device
        # then find in which device that partition resides
        dev="$(basename "$(readlink -f /sys/class/block/"$(ls /sys/class/block/"$(basename "$(readlink -f /dev/mapper/$VG)")"/slaves)"/..)")"
        grub-install --target=i386-pc /dev/$dev
        grub-install --target=i386-pc --force /dev/$dev'1'
    fi
}

function funcMirrorlist {
    reflector --latest 25 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
    rm -f /etc/pacman.d/mirrorlist.pacnew
}

function funcTheme {
    # Backup New Update
    cp /usr/share/themes/Arc/gtk-2.0/gtkrc /usr/share/themes/Arc/gtk-2.0/gtkrc.bk
    cp /usr/share/themes/Arc/gtk-3.0/gtk.gresource /usr/share/themes/Arc/gtk-3.0/gtk.gresource.bk
    cp /usr/share/themes/Arc-Dark/gtk-2.0/gtkrc /usr/share/themes/Arc-Dark/gtk-2.0/gtkrc.bk
    cp /usr/share/themes/Arc-Dark/gtk-3.0/gtk.gresource /usr/share/themes/Arc-Dark/gtk-3.0/gtk.gresource.bk
    # User Preferences
    cp /home/user/.config/monocleOS/arc_gtk2_gtkrc /usr/share/themes/Arc/gtk-2.0/gtkrc
    cp /home/user/.config/monocleOS/arc_gtk3_gtk_gresource /usr/share/themes/Arc/gtk-3.0/gtk.gresource
    cp /home/user/.config/monocleOS/arc_dark_gtk2_gtkrc /usr/share/themes/Arc-Dark/gtk-2.0/gtkrc
    cp /home/user/.config/monocleOS/arc_dark_gtk3_gtk_gresource /usr/share/themes/Arc-Dark/gtk-3.0/gtk.gresource
}

case "$1" in
    --grub)
        funcGrub
        ;;
    --mirrorlist)
        funcMirrorlist
        ;;
    --theme)
        funcTheme
        ;;
    *)
        funcSystem
        ;;
esac
